name: deploy to lambda
on:
    push:
        branches: [main]
        paths:
         - 'lambda-test/**'
jobs:
  deploy_source:
    name: Deploy Lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_2 }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_2 }}
          aws_region: us-east-1
          function_name: test
          zip_file: lambda-test/lambda_function.zip
